### ISSUE TITLE
error while running inference.sh in summarization module error: argument --task: invalid choice: 'translation_lev_modified'

### ISSUE THREAD

**Issue by vfbi** [hemingkx/GAD#2]
while running error inference.sh in summarization module with sh inference.sh then getting the
error: argument --task: invalid choice: 'translation_lev_modified' (choose from 'cross_lingual_lm', 'audio_pretraining', 'hubert_pretraining', 'multilingual_masked_lm', 'language_modeling', 'masked_lm', 'sentence_prediction', 'sentence_prediction_adapters', 'multilingual_language_modeling', 'translation', 'translation_from_pretrained_bart', 'speech_to_text', 'text_to_speech', 'speech_to_speech', 'audio_finetuning', 'translation_from_pretrained_xlm', 'frm_text_to_speech', 'speech_unit_modeling', 'multilingual_translation', 'online_backtranslation', 'denoising', 'translation_multi_simple_epoch', 'multilingual_denoising', 'legacy_masked_lm', 'semisupervised_translation', 'translation_lev', 'simul_speech_to_text', 'simul_text_to_text', 'sentence_ranking', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt')

**Comment by hemingkx** [comment]
The codes of  'translation_lev_modified' is [here](https://github.com/hemingkx/GAD/blob/main/block_plugins/tasks/translation_lev_modified.py#L47).
Please follow the [installation guide](https://github.com/hemingkx/GAD#installation) especially 'pip install --editable .', then try to run inference.sh again.

If you have any other problem, feel free to leave a message.

**Comment by hemingkx** [comment]
We have updated our files in [summarization installation](https://github.com/hemingkx/GAD/tree/main/summarization#installation) and [inference.sh](https://github.com/hemingkx/GAD/blob/main/summarization/inference.sh), please check again if something is missing.

**Comment by vfbi** [comment]
Hi,
As per your instruction we had installed 
1)installed pip install --editable .
2)pip install requests
already downloaded cnn-dm-base-nat-drafter-checkpoint.avg10.pt,cnn-dm-base-at-verifier.pt,test.source,test.target
set the appropriate path in inference.sh as below
checkpoint_path=cnn-dm-base-nat-drafter-checkpoint.avg10.pt, AR_checkpoint_path=cnn-dm-base-at-verifier.pt,
input_path=test.source ,data=./data(this directory contains dict.target.txt,dict.source.txt)
still getting same error inference_paper.py: error: argument --task: invalid choice: 'translation_lev_modified' (choose from 'cross_lingual_lm', 'audio_pretraining', 'multilingual_masked_lm', 'masked_lm', 'translation', 'translation_from_pretrained_bart', 'translation_from_pretrained_xlm', 'speech_to_text', 'multilingual_translation', 'denoising', 'sentence_prediction', 'translation_multi_simple_epoch', 'multilingual_denoising', 'legacy_masked_lm', 'semisupervised_translation', 'language_modeling', 'translation_lev', 'sentence_ranking', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt')

**Comment by hemingkx** [comment]
Here is the correct inference command:

```
python inference_paper.py $data_dir --path $checkpoint_path --user-dir block_plugins \
      --task translation_lev_modified --remove-bpe --max-sentences 20 --source-lang source \
      --target-lang target --iter-decode-max-iter 0 --iter-decode-eos-penalty 0 --iter-decode-with-beam 1 \
      --gen-subset test --strategy ${strategy} --AR-path $AR_checkpoint_path --input-path $input_path \
      --output-path $output_path --batch ${batch} --block-size ${block_size} --beam ${beam} --max-len ${max_len} \
      --beta ${beta} --tau ${tau}
```

This error (invalid choice: 'translation_lev_modified') is because you did not specify the `--user-dir` path correctly, it should be the path [here](https://github.com/hemingkx/GAD/tree/main/block_plugins). This folder defines the task `translation_lev_modified`.

Please check if you set the `--user-dir` path correctly.

If this path is loaded correctly, the command line will output (as defined [here](https://github.com/hemingkx/GAD/blob/main/block_plugins/__init__.py#L5)):

```
GAD plugins loaded...
2023-02-24 09:35:05 | INFO | fairseq.tasks.translation |  [translation.py:313] [source] dictionary: 51200 types
2023-02-24 09:35:05 | INFO | fairseq.tasks.translation |  [translation.py:314] [target] dictionary: 51200 types
2023-02-24 09:35:05 | INFO | inference |  [inference_paper.py:286] loading model(s) from...
```

**Comment by vfbi** [comment]
Thanks after changing the --user-dir path code is running
